// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

@freezed
sealed class EncryptionInfo with _$EncryptionInfo {
  const factory EncryptionInfo({
    required bool isEncrypted,
    required int pageCount,
  }) = _EncryptionInfo;
}

@freezed
sealed class FileInfo with _$FileInfo {
  const factory FileInfo({
    required String path,
    required int sizeBytes,
    required int pageCount,
    required bool isEncrypted,
  }) = _FileInfo;
}

@freezed
sealed class PdfResult with _$PdfResult {
  const factory PdfResult({
    required bool success,
    required String outputPath,
    String? error,
    required int pageCount,
    required int processingMs,
  }) = _PdfResult;
}
