// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pdf_ops.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2136196993;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_pdftoolkit',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PdfResult> crateApiPdfOpsCompressPdf({
    required String inputPath,
    required String outputPath,
    required int quality,
  });

  Future<FileInfo> crateApiPdfOpsGetFileInfo({required String path});

  Future<EncryptionInfo> crateApiPdfOpsGetPdfEncryptionInfo({
    required String path,
  });

  Future<int> crateApiPdfOpsGetPdfPageCount({required String path});

  String crateApiSimpleGreet({required String name});

  Future<PdfResult> crateApiPdfOpsImagesToPdf({
    required List<String> imagePaths,
    required String outputPath,
    required bool addWatermark,
  });

  Future<void> crateApiSimpleInitApp();

  Future<PdfResult> crateApiPdfOpsMergePdfs({
    required List<String> paths,
    required String outputPath,
    required bool addWatermark,
  });

  Future<PdfResult> crateApiPdfOpsPdfToImages({
    required String inputPath,
    required String outputDir,
    required int dpi,
  });

  Future<PdfResult> crateApiPdfOpsProtectPdf({
    required String inputPath,
    required String password,
    required String outputPath,
  });

  Future<PdfResult> crateApiPdfOpsSignPdf({
    required String inputPath,
    required String outputPath,
    required String sigImagePath,
    required String signerName,
    required int pageNumber,
    required double x,
    required double y,
    required double width,
    required double height,
  });

  Future<PdfResult> crateApiPdfOpsSplitPdf({
    required String inputPath,
    required List<int> pages,
    required String outputPath,
    required bool addWatermark,
  });

  Future<PdfResult> crateApiPdfOpsTextToPdf({
    required String textContent,
    required String outputPath,
    required String title,
    required double fontSize,
  });

  Future<PdfResult> crateApiPdfOpsUnlockPdf({
    required String inputPath,
    required String password,
    required String outputPath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PdfResult> crateApiPdfOpsCompressPdf({
    required String inputPath,
    required String outputPath,
    required int quality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_u_32(quality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsCompressPdfConstMeta,
        argValues: [inputPath, outputPath, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsCompressPdfConstMeta => const TaskConstMeta(
    debugName: "compress_pdf",
    argNames: ["inputPath", "outputPath", "quality"],
  );

  @override
  Future<FileInfo> crateApiPdfOpsGetFileInfo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_file_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsGetFileInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsGetFileInfoConstMeta =>
      const TaskConstMeta(debugName: "get_file_info", argNames: ["path"]);

  @override
  Future<EncryptionInfo> crateApiPdfOpsGetPdfEncryptionInfo({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encryption_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsGetPdfEncryptionInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsGetPdfEncryptionInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_pdf_encryption_info",
        argNames: ["path"],
      );

  @override
  Future<int> crateApiPdfOpsGetPdfPageCount({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsGetPdfPageCountConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsGetPdfPageCountConstMeta =>
      const TaskConstMeta(debugName: "get_pdf_page_count", argNames: ["path"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<PdfResult> crateApiPdfOpsImagesToPdf({
    required List<String> imagePaths,
    required String outputPath,
    required bool addWatermark,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(imagePaths, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_bool(addWatermark, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsImagesToPdfConstMeta,
        argValues: [imagePaths, outputPath, addWatermark],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsImagesToPdfConstMeta => const TaskConstMeta(
    debugName: "images_to_pdf",
    argNames: ["imagePaths", "outputPath", "addWatermark"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PdfResult> crateApiPdfOpsMergePdfs({
    required List<String> paths,
    required String outputPath,
    required bool addWatermark,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_bool(addWatermark, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsMergePdfsConstMeta,
        argValues: [paths, outputPath, addWatermark],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsMergePdfsConstMeta => const TaskConstMeta(
    debugName: "merge_pdfs",
    argNames: ["paths", "outputPath", "addWatermark"],
  );

  @override
  Future<PdfResult> crateApiPdfOpsPdfToImages({
    required String inputPath,
    required String outputDir,
    required int dpi,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputDir, serializer);
          sse_encode_u_32(dpi, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsPdfToImagesConstMeta,
        argValues: [inputPath, outputDir, dpi],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsPdfToImagesConstMeta => const TaskConstMeta(
    debugName: "pdf_to_images",
    argNames: ["inputPath", "outputDir", "dpi"],
  );

  @override
  Future<PdfResult> crateApiPdfOpsProtectPdf({
    required String inputPath,
    required String password,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsProtectPdfConstMeta,
        argValues: [inputPath, password, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsProtectPdfConstMeta => const TaskConstMeta(
    debugName: "protect_pdf",
    argNames: ["inputPath", "password", "outputPath"],
  );

  @override
  Future<PdfResult> crateApiPdfOpsSignPdf({
    required String inputPath,
    required String outputPath,
    required String sigImagePath,
    required String signerName,
    required int pageNumber,
    required double x,
    required double y,
    required double width,
    required double height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_String(sigImagePath, serializer);
          sse_encode_String(signerName, serializer);
          sse_encode_u_32(pageNumber, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(width, serializer);
          sse_encode_f_64(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsSignPdfConstMeta,
        argValues: [
          inputPath,
          outputPath,
          sigImagePath,
          signerName,
          pageNumber,
          x,
          y,
          width,
          height,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsSignPdfConstMeta => const TaskConstMeta(
    debugName: "sign_pdf",
    argNames: [
      "inputPath",
      "outputPath",
      "sigImagePath",
      "signerName",
      "pageNumber",
      "x",
      "y",
      "width",
      "height",
    ],
  );

  @override
  Future<PdfResult> crateApiPdfOpsSplitPdf({
    required String inputPath,
    required List<int> pages,
    required String outputPath,
    required bool addWatermark,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_list_prim_u_32_loose(pages, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_bool(addWatermark, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsSplitPdfConstMeta,
        argValues: [inputPath, pages, outputPath, addWatermark],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsSplitPdfConstMeta => const TaskConstMeta(
    debugName: "split_pdf",
    argNames: ["inputPath", "pages", "outputPath", "addWatermark"],
  );

  @override
  Future<PdfResult> crateApiPdfOpsTextToPdf({
    required String textContent,
    required String outputPath,
    required String title,
    required double fontSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(textContent, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_f_64(fontSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsTextToPdfConstMeta,
        argValues: [textContent, outputPath, title, fontSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsTextToPdfConstMeta => const TaskConstMeta(
    debugName: "text_to_pdf",
    argNames: ["textContent", "outputPath", "title", "fontSize"],
  );

  @override
  Future<PdfResult> crateApiPdfOpsUnlockPdf({
    required String inputPath,
    required String password,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfOpsUnlockPdfConstMeta,
        argValues: [inputPath, password, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfOpsUnlockPdfConstMeta => const TaskConstMeta(
    debugName: "unlock_pdf",
    argNames: ["inputPath", "password", "outputPath"],
  );

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EncryptionInfo dco_decode_encryption_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EncryptionInfo(
      isEncrypted: dco_decode_bool(arr[0]),
      pageCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileInfo dco_decode_file_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FileInfo(
      path: dco_decode_String(arr[0]),
      sizeBytes: dco_decode_CastedPrimitive_u_64(arr[1]),
      pageCount: dco_decode_u_32(arr[2]),
      isEncrypted: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PdfResult dco_decode_pdf_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PdfResult(
      success: dco_decode_bool(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      error: dco_decode_opt_String(arr[2]),
      pageCount: dco_decode_u_32(arr[3]),
      processingMs: dco_decode_CastedPrimitive_u_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EncryptionInfo sse_decode_encryption_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isEncrypted = sse_decode_bool(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    return EncryptionInfo(
      isEncrypted: var_isEncrypted,
      pageCount: var_pageCount,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileInfo sse_decode_file_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    return FileInfo(
      path: var_path,
      sizeBytes: var_sizeBytes,
      pageCount: var_pageCount,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfResult sse_decode_pdf_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    var var_processingMs = sse_decode_CastedPrimitive_u_64(deserializer);
    return PdfResult(
      success: var_success,
      outputPath: var_outputPath,
      error: var_error,
      pageCount: var_pageCount,
      processingMs: var_processingMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_encryption_info(
    EncryptionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isEncrypted, serializer);
    sse_encode_u_32(self.pageCount, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_info(FileInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_CastedPrimitive_u_64(self.sizeBytes, serializer);
    sse_encode_u_32(self.pageCount, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(
      self is Uint32List ? self : Uint32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_pdf_result(PdfResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_u_32(self.pageCount, serializer);
    sse_encode_CastedPrimitive_u_64(self.processingMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
