// This is a stub file for the flutter_rust_bridge generated code.
// The real file will be generated by the user once they fix their rust/cargo environment
// and run: flutter_rust_bridge_codegen generate

// ignore_for_file: unused_import, unused_element

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RustLib {
  static Future<void> init() async {}
}

class PdfResult {
  final bool success;
  final String outputPath;
  final String? error;
  final int pageCount;
  final int processingMs;

  PdfResult({
    required this.success,
    required this.outputPath,
    this.error,
    this.pageCount = 0,
    this.processingMs = 0,
  });
}

class FileInfo {
  final String path;
  final int sizeBytes;
  final int pageCount;
  final bool isEncrypted;

  FileInfo({
    required this.path,
    required this.sizeBytes,
    required this.pageCount,
    required this.isEncrypted,
  });
}

class EncryptionInfo {
  final bool isEncrypted;
  final int pageCount;

  EncryptionInfo({required this.isEncrypted, required this.pageCount});
}

Future<PdfResult> mergePdfs({
  required List<String> paths,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> splitPdf({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
  bool addWatermark = false,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> protectPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> unlockPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> imagesToPdf({
  required List<String> imagePaths,
  required String outputPath,
  bool addWatermark = false,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> checkPdfEncrypted({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<EncryptionInfo> getPdfEncryptionInfo({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<int> getPdfPageCount({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<FileInfo> getFileInfo({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> deleteFile({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> fileExists({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}
