// This is a stub file for the flutter_rust_bridge generated code.
// The real file will be generated by the user once they fix their rust/cargo environment
// and run: flutter_rust_bridge_codegen generate

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RustLib {
  static Future<void> init() async {}
}

class PdfResult {
  final bool success;
  final String outputPath;
  final String? error;

  PdfResult({required this.success, required this.outputPath, this.error});
}

class PageInfo {
  final int pageNumber;
  final double? width;
  final double? height;

  PageInfo({required this.pageNumber, this.width, this.height});
}

class FileInfo {
  final String path;
  final int sizeBytes;
  final int pageCount;
  final bool isEncrypted;

  FileInfo({
    required this.path,
    required this.sizeBytes,
    required this.pageCount,
    required this.isEncrypted,
  });
}

class EncryptionInfo {
  final bool isEncrypted;
  final int pageCount;

  EncryptionInfo({required this.isEncrypted, required this.pageCount});
}

class CompressionInfo {
  final int pageCount;
  final int streamCount;
  final int compressedStreams;

  CompressionInfo({
    required this.pageCount,
    required this.streamCount,
    required this.compressedStreams,
  });
}

Future<PdfResult> mergePdfs({
  required List<String> paths,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> splitPdf({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> extractPdfPages({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<List<String>> splitPdfToSinglePages({
  required String inputPath,
  required String outputDir,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> protectPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> unlockPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> checkPdfEncrypted({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<EncryptionInfo> getPdfEncryptionInfo({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<PdfResult> compressPdfFile({
  required String inputPath,
  required int level,
  required String outputPath,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<CompressionInfo> getPdfCompressionInfo({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<int> getPdfPageCount({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<int> getPdfFileSize({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<List<int>> getPdfPages({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<String> getAppDocumentsDir() async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<String> getOutputDirectory() async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<String> generateOutputFilename({
  required String prefix,
  required String extension,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<String> copyFile({
  required String source,
  required String destination,
}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> deleteFile({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}

Future<bool> fileExists({required String path}) async {
  throw UnimplementedError(
    "Rust native engine not linked. Run 'flutter_rust_bridge_codegen generate' and recompile.",
  );
}
