// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.
// New functions added manually — re-run `flutter_rust_bridge_codegen generate`
// to regenerate frb_generated.dart after adding Rust functions.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `add_watermark_to_doc`,
// `add_watermark_to_page`, `compute_o_entry`, `compute_u_entry`, `err`, `fit_to_a4`,
// `get_pages_id`, `images_to_pdf_inner`, `merge_pdfs_inner`, `now_ms`, `ok`, `pad_password`,
// `protect_pdf_inner`, `remap_dict`, `remap_ids`, `remap_object`, `split_pdf_inner`,
// `unlock_pdf_inner`, `pdf_to_images_inner`, `compress_pdf_inner`, `sign_pdf_inner`,
// `text_to_pdf_inner`, `get_page_dimensions`, `composite_page_images`, `parse_image_placements`,
// `pdf_escape`, `sign_with_image`, `sign_with_text`, `inject_sig_resources`,
// `get_xobject_dict`, `get_page_content_bytes`, `ensure_f1_in_resources_dict`

/// Merge multiple PDFs into one output file.
Future<PdfResult> mergePdfs({
  required List<String> paths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsMergePdfs(
  paths: paths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Split a PDF: extract specific pages (1-indexed) into a new file.
Future<PdfResult> splitPdf({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsSplitPdf(
  inputPath: inputPath,
  pages: pages,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Protect a PDF with AES password encryption.
Future<PdfResult> protectPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsProtectPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Unlock (remove password from) a PDF.
Future<PdfResult> unlockPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsUnlockPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Convert images to a single PDF.
Future<PdfResult> imagesToPdf({
  required List<String> imagePaths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsImagesToPdf(
  imagePaths: imagePaths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Convert each page of a PDF to a JPEG image.
/// Returns a PdfResult where outputPath is '|'-joined list of saved image paths.
Future<PdfResult> pdfToImages({
  required String inputPath,
  required String outputDir,
  required int dpi,
}) => RustLib.instance.api.crateApiPdfOpsPdfToImages(
  inputPath: inputPath,
  outputDir: outputDir,
  dpi: dpi,
);

/// Compress a PDF by re-encoding JPEG images at lower quality.
/// quality: 1–100 (recommended: 60 high compression, 80 balanced, 90 low).
Future<PdfResult> compressPdf({
  required String inputPath,
  required String outputPath,
  required int quality,
}) => RustLib.instance.api.crateApiPdfOpsCompressPdf(
  inputPath: inputPath,
  outputPath: outputPath,
  quality: quality,
);

/// Add a visible signature to a PDF page.
/// sigImagePath: optional path to PNG/JPEG signature image; leave empty to use text.
/// signerName: display name shown under the signature.
/// pageNumber: 1-indexed page to place signature on.
/// x, y: position in points from bottom-left of page.
/// width, height: signature box dimensions in points.
Future<PdfResult> signPdf({
  required String inputPath,
  required String outputPath,
  required String sigImagePath,
  required String signerName,
  required int pageNumber,
  required double x,
  required double y,
  required double width,
  required double height,
}) => RustLib.instance.api.crateApiPdfOpsSignPdf(
  inputPath: inputPath,
  outputPath: outputPath,
  sigImagePath: sigImagePath,
  signerName: signerName,
  pageNumber: pageNumber,
  x: x,
  y: y,
  width: width,
  height: height,
);

/// Convert plain-text content to a paginated PDF.
/// textContent: raw UTF-8 text (pre-extracted from DOCX / CSV / XLSX by Dart side).
/// title: shown as a bold header on page 1.
/// fontSize: point size (8–16 recommended).
Future<PdfResult> textToPdf({
  required String textContent,
  required String outputPath,
  required String title,
  required double fontSize,
}) => RustLib.instance.api.crateApiPdfOpsTextToPdf(
  textContent: textContent,
  outputPath: outputPath,
  title: title,
  fontSize: fontSize,
);

/// Get page count of a PDF.
Future<int> getPdfPageCount({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfPageCount(path: path);

/// Get file info.
Future<FileInfo> getFileInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetFileInfo(path: path);

/// Check if PDF is encrypted.
Future<EncryptionInfo> getPdfEncryptionInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfEncryptionInfo(path: path);
