// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `add_watermark_to_doc`, `add_watermark_to_page`, `compute_o_entry`, `compute_u_entry`, `err`, `fit_to_a4`, `get_pages_id`, `images_to_pdf_inner`, `merge_pdfs_inner`, `now_ms`, `ok`, `pad_password`, `protect_pdf_inner`, `remap_dict`, `remap_ids`, `remap_object`, `split_pdf_inner`, `unlock_pdf_inner`

/// Merge multiple PDFs into one output file.
Future<PdfResult> mergePdfs({
  required List<String> paths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsMergePdfs(
  paths: paths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Split a PDF: extract specific pages (1-indexed) into a new file.
Future<PdfResult> splitPdf({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsSplitPdf(
  inputPath: inputPath,
  pages: pages,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Protect a PDF with AES password encryption.
Future<PdfResult> protectPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsProtectPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Unlock (remove password from) a PDF.
Future<PdfResult> unlockPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsUnlockPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Convert images to a single PDF.
Future<PdfResult> imagesToPdf({
  required List<String> imagePaths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsImagesToPdf(
  imagePaths: imagePaths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Get page count of a PDF.
Future<int> getPdfPageCount({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfPageCount(path: path);

/// Get file info.
Future<FileInfo> getFileInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetFileInfo(path: path);

/// Check if PDF is encrypted.
Future<EncryptionInfo> getPdfEncryptionInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfEncryptionInfo(path: path);
