// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `add_watermark_to_doc`, `add_watermark_to_page`, `composite_page_images`, `compress_pdf_inner`, `ensure_f1_in_resources_dict`, `err`, `fit_to_a4`, `get_page_content_bytes`, `get_page_dimensions`, `get_pages_id`, `get_xobject_dict`, `images_to_pdf_inner`, `inject_sig_resources`, `merge_pdfs_inner`, `now_ms`, `ok_multi`, `ok`, `parse_image_placements`, `pdf_escape`, `pdf_to_images_inner`, `protect_pdf_inner`, `remap_dict`, `remap_ids`, `remap_object`, `sign_pdf_inner`, `sign_with_image`, `sign_with_text`, `split_pdf_inner`, `text_to_pdf_inner`, `unlock_pdf_inner`

/// Merge multiple PDFs into one output file.
Future<PdfResult> mergePdfs({
  required List<String> paths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsMergePdfs(
  paths: paths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Split a PDF: extract specific pages (1-indexed) into a new file.
Future<PdfResult> splitPdf({
  required String inputPath,
  required List<int> pages,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsSplitPdf(
  inputPath: inputPath,
  pages: pages,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Protect a PDF with password encryption.
Future<PdfResult> protectPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsProtectPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Unlock (remove password from) a PDF.
Future<PdfResult> unlockPdf({
  required String inputPath,
  required String password,
  required String outputPath,
}) => RustLib.instance.api.crateApiPdfOpsUnlockPdf(
  inputPath: inputPath,
  password: password,
  outputPath: outputPath,
);

/// Convert images to a single PDF.
Future<PdfResult> imagesToPdf({
  required List<String> imagePaths,
  required String outputPath,
  required bool addWatermark,
}) => RustLib.instance.api.crateApiPdfOpsImagesToPdf(
  imagePaths: imagePaths,
  outputPath: outputPath,
  addWatermark: addWatermark,
);

/// Convert each page of a PDF to a JPEG image.
/// Returns a PdfResult where output_path is '|'-joined list of image paths.
/// output_dir: directory to save images into.
/// dpi: rendering DPI (72 = screen, 150 = medium, 300 = print).
/// Currently renders via a simple pixel-level approach using lopdf + image crate.
Future<PdfResult> pdfToImages({
  required String inputPath,
  required String outputDir,
  required int dpi,
}) => RustLib.instance.api.crateApiPdfOpsPdfToImages(
  inputPath: inputPath,
  outputDir: outputDir,
  dpi: dpi,
);

/// Compress a PDF by re-encoding JPEG images at lower quality and
/// removing metadata / unused objects.
/// quality: JPEG quality 1-100 (suggested: 60 for high compression, 80 for balanced)
Future<PdfResult> compressPdf({
  required String inputPath,
  required String outputPath,
  required int quality,
}) => RustLib.instance.api.crateApiPdfOpsCompressPdf(
  inputPath: inputPath,
  outputPath: outputPath,
  quality: quality,
);

/// Add a visible text/image signature to a PDF page.
/// sig_image_path: optional path to a PNG/JPEG signature image; if empty, uses text.
/// signer_name: display name shown in signature.
/// page_number: 1-indexed page to place signature on.
/// x, y: position in points from bottom-left.
/// width, height: signature box dimensions in points.
Future<PdfResult> signPdf({
  required String inputPath,
  required String outputPath,
  required String sigImagePath,
  required String signerName,
  required int pageNumber,
  required double x,
  required double y,
  required double width,
  required double height,
}) => RustLib.instance.api.crateApiPdfOpsSignPdf(
  inputPath: inputPath,
  outputPath: outputPath,
  sigImagePath: sigImagePath,
  signerName: signerName,
  pageNumber: pageNumber,
  x: x,
  y: y,
  width: width,
  height: height,
);

/// Convert a plain-text file (DOCX exported as .txt, CSV, or raw text) to PDF.
/// For DOCX: caller should extract text content before calling (e.g. via docx_rs).
/// This function takes raw UTF-8 text lines and renders them as a paginated PDF.
/// font_size: point size (suggested 11-12).
Future<PdfResult> textToPdf({
  required String textContent,
  required String outputPath,
  required String title,
  required double fontSize,
}) => RustLib.instance.api.crateApiPdfOpsTextToPdf(
  textContent: textContent,
  outputPath: outputPath,
  title: title,
  fontSize: fontSize,
);

/// Get page count of a PDF.
Future<int> getPdfPageCount({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfPageCount(path: path);

/// Get file info.
Future<FileInfo> getFileInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetFileInfo(path: path);

/// Check if PDF is encrypted.
Future<EncryptionInfo> getPdfEncryptionInfo({required String path}) =>
    RustLib.instance.api.crateApiPdfOpsGetPdfEncryptionInfo(path: path);
